# 1.0 - Primeiros passos
1.1 - Importanto PANDA e NUMPY 

1.2 - Importanto data frame (aqui usaremos o arquivo CSV dado pelo site kaggle)  

1.3 - Leituras iniciais do data frame, utilizando info(), head(), describe()

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("attacks.csv", sep=",", encoding='cp1251')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Case Number             8702 non-null   object 
 1   Date                    6302 non-null   object 
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object 
 4   Country                 6252 non-null   object 
 5   Area                    5847 non-null   object 
 6   Location                5762 non-null   object 
 7   Activity                5758 non-null   object 
 8   Name                    6092 non-null   object 
 9   Sex                     5737 non-null   object 
 10  Age                     3471 non-null   object 
 11  Injury                  6274 non-null   object 
 12  Fatal (Y/N)             5763 non-null   object 
 13  Time                    2948 non-null   object 
 14  Species                 3464 non-null 

In [3]:
data.describe()

Year  original order
count  6300.000000     6309.000000
mean   1927.272381     3155.999683
std     281.116308     1821.396206
min       0.000000        2.000000
25%    1942.000000     1579.000000
50%    1977.000000     3156.000000
75%    2005.000000     4733.000000
max    2018.000000     6310.000000

In [4]:
data.head()

Case Number         Date    Year        Type    Country             Area  \
0  2018.06.25  25-Jun-2018  2018.0     Boating        USA       California   
1  2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA          Georgia   
2  2018.06.09  09-Jun-2018  2018.0     Invalid        USA           Hawaii   
3  2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA  New South Wales   
4  2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO           Colima   

                         Location     Activity             Name Sex   ...  \
0     Oceanside, San Diego County     Paddling      Julie Wolfe    F  ...   
1  St. Simon Island, Glynn County     Standing  Adyson McNeely     F  ...   
2                    Habush, Oahu      Surfing      John Denges    M  ...   
3              Arrawarra Headland      Surfing             male    M  ...   
4                        La Ticla  Free diving   Gustavo Ramos     M  ...   

          Species           Investigator or Source                       pdf  \
0      White shark                R. Collier, GSAF      2018.06.25-Wolfe.pdf   
1              NaN  K.McMurray, TrackingSharks.com    2018.06.18-McNeely.pdf   
2              NaN  K.McMurray, TrackingSharks.com     2018.06.09-Denges.pdf   
3        2 m shark                  B. Myatt, GSAF  2018.06.08-Arrawarra.pdf   
4  Tiger shark, 3m                       A .Kipper      2018.06.04-Ramos.pdf   

                                        href formula  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...   
1  http://sharkattackfile.net/spreadsheets/pdf_di...   
2  http://sharkattackfile.net/spreadsheets/pdf_di...   
3  http://sharkattackfile.net/spreadsheets/pdf_di...   
4  http://sharkattackfile.net/spreadsheets/pdf_di...   

                                                href Case Number.1  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25   
1  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18   
2  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09   
3  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.08   
4  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.04   

  Case Number.2 original order Unnamed: 22 Unnamed: 23  
0    2018.06.25         6303.0         NaN         NaN  
1    2018.06.18         6302.0         NaN         NaN  
2    2018.06.09         6301.0         NaN         NaN  
3    2018.06.08         6300.0         NaN         NaN  
4    2018.06.04         6299.0         NaN         NaN  

[5 rows x 24 columns]

# 2.0 - Limpeza
2.1 - Verificando se há valores NULOS

2.2 - Analisamos a partir de qual linha aproximadamente tínhamos apenas valores NULOS para todas as colunas

2.3 - Fizemos uma somatória de todos os valores nulos para termos uma ideia de quantos estamos falando 

2.4 - Aplicamos o comando **dropna** para retirar as LINHAS cujos inputs eram todos nulos 

2.5 - Aplicamos o comando **drop** para retirar as COLUNAS que inicalmente não traziam nenhum informação relevante 

2.6 - Aplicamos o comando **drop_duplicates()** para retirar linhas que tinham apenas 2 ou 3 inputs de informação apenas, e cujos inputs eram informações sem sentido 

2.7 - Dropamos as linhas 6302 e 25722 cujos valores tinham informações específicas irrelevanetes e muitos nulos

2.8 - Padronizamos a nomeclatura das colunas - retiramos espaços e deixamos todas as palavras em minúsculo

2.9 - Renomeamos a coluna _sex_ para _gender_

In [5]:
#2.1
data.isnull().values.any()

True

In [6]:
#2.2
data.iloc[6300:25841, 0:20]

Case Number       Date  Year        Type             Country  \
6300      ND.0002  1883-1889   0.0  Unprovoked              PANAMA   
6301      ND.0001  1845-1853   0.0  Unprovoked  CEYLON (SRI LANKA)   
6302            0        NaN   NaN         NaN                 NaN   
6303            0        NaN   NaN         NaN                 NaN   
6304            0        NaN   NaN         NaN                 NaN   
...           ...        ...   ...         ...                 ...   
25718         NaN        NaN   NaN         NaN                 NaN   
25719         NaN        NaN   NaN         NaN                 NaN   
25720         NaN        NaN   NaN         NaN                 NaN   
25721         NaN        NaN   NaN         NaN                 NaN   
25722          xx        NaN   NaN         NaN                 NaN   

                   Area                             Location  Activity  \
6300                NaN                 Panama Bay 8єN, 79єW       NaN   
6301   Eastern Province  Below the English fort, Trincomalee  Swimming   
6302                NaN                                  NaN       NaN   
6303                NaN                                  NaN       NaN   
6304                NaN                                  NaN       NaN   
...                 ...                                  ...       ...   
25718               NaN                                  NaN       NaN   
25719               NaN                                  NaN       NaN   
25720               NaN                                  NaN       NaN   
25721               NaN                                  NaN       NaN   
25722               NaN                                  NaN       NaN   

                  Name Sex   Age  \
6300   Jules Patterson    M  NaN   
6301              male    M   15   
6302               NaN  NaN  NaN   
6303               NaN  NaN  NaN   
6304               NaN  NaN  NaN   
...                ...  ...  ...   
25718              NaN  NaN  NaN   
25719              NaN  NaN  NaN   
25720              NaN  NaN  NaN   
25721              NaN  NaN  NaN   
25722              NaN  NaN  NaN   

                                                  Injury Fatal (Y/N) Time  \
6300                                               FATAL           Y  NaN   
6301   FATAL. "Shark bit him in half, carrying away t...           Y  NaN   
6302                                                 NaN         NaN  NaN   
6303                                                 NaN         NaN  NaN   
6304                                                 NaN         NaN  NaN   
...                                                  ...         ...  ...   
25718                                                NaN         NaN  NaN   
25719                                                NaN         NaN  NaN   
25720                                                NaN         NaN  NaN   
25721                                                NaN         NaN  NaN   
25722                                                NaN         NaN  NaN   

      Species  Investigator or Source                         pdf  \
6300       NaN    The Sun, 10/20/1938  ND-0002-JulesPatterson.pdf   
6301       NaN             S.W. Baker          ND-0001-Ceylon.pdf   
6302       NaN                    NaN                         NaN   
6303       NaN                    NaN                         NaN   
6304       NaN                    NaN                         NaN   
...        ...                    ...                         ...   
25718      NaN                    NaN                         NaN   
25719      NaN                    NaN                         NaN   
25720      NaN                    NaN                         NaN   
25721      NaN                    NaN                         NaN   
25722      NaN                    NaN                         NaN   

                                            href formula  \
6300   http://sharkattackfile

In [7]:
#2.3
data.isnull().sum()

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [8]:
#2.4
data_limpo = data.dropna(how="all")
data_limpo

Case Number         Date    Year        Type    Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating        USA   
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA   
2      2018.06.09  09-Jun-2018  2018.0     Invalid        USA   
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA   
4      2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO   
...           ...          ...     ...         ...        ...   
8698            0          NaN     NaN         NaN        NaN   
8699            0          NaN     NaN         NaN        NaN   
8700            0          NaN     NaN         NaN        NaN   
8701            0          NaN     NaN         NaN        NaN   
25722          xx          NaN     NaN         NaN        NaN   

                  Area                        Location     Activity  \
0           California     Oceanside, San Diego County     Paddling   
1              Georgia  St. Simon Island, Glynn County     Standing   
2               Hawaii                    Habush, Oahu      Surfing   
3      New South Wales              Arrawarra Headland      Surfing   
4               Colima                        La Ticla  Free diving   
...                ...                             ...          ...   
8698               NaN                             NaN          NaN   
8699               NaN                             NaN          NaN   
8700               NaN                             NaN          NaN   
8701               NaN                             NaN          NaN   
25722              NaN                             NaN          NaN   

                  Name Sex   ...         Species   \
0          Julie Wolfe    F  ...      White shark   
1      Adyson McNeely     F  ...              NaN   
2          John Denges    M  ...              NaN   
3                 male    M  ...        2 m shark   
4       Gustavo Ramos     M  ...  Tiger shark, 3m   
...                ...  ...  ...              ...   
8698               NaN  NaN  ...              NaN   
8699               NaN  NaN  ...              NaN   
8700               NaN  NaN  ...              NaN   
8701               NaN  NaN  ...              NaN   
25722              NaN  NaN  ...              NaN   

               Investigator or Source                       pdf  \
0                    R. Collier, GSAF      2018.06.25-Wolfe.pdf   
1      K.McMurray, TrackingSharks.com    2018.06.18-McNeely.pdf   
2      K.McMurray, TrackingSharks.com     2018.06.09-Denges.pdf   
3                      B. Myatt, GSAF  2018.06.08-Arrawarra.pdf   
4                           A .Kipper      2018.06.04-Ramos.pdf   
...                               ...                       ...   
8698                              NaN                       NaN   
8699                              NaN                       NaN   
8700                              NaN                       NaN   
8701                              NaN                       NaN   
25722                             NaN                       NaN   

                                            href formula  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...   
1      http://sharkattackfile.net/spreadsheets/pdf_di...   
2      http://sharkattackfile.net/spreadsheets/pdf_di...   
3      http://sharkattackfile.net/spreadsheets/pdf_di...   
4      http://sharkattackfile.net/spreadsheets/pdf_di...   
...                                                  ...   
8698                                                 NaN   
8699                                                 NaN   
8700                                                 NaN   
8701                                                 NaN   
25722                                                NaN   

                                                    href Case Number.1  \
0      http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25   
1      http://sharkattackfile.net/spreadsheets/pdf_di...    2

In [9]:
#2.5
data_limpo2 = data_limpo.drop(columns=['Unnamed: 22', 'Unnamed: 23','href formula','href','Case Number.1','Case Number.2','original order','Investigator or Source','pdf'])
data_limpo2

Case Number         Date    Year        Type    Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating        USA   
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA   
2      2018.06.09  09-Jun-2018  2018.0     Invalid        USA   
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA   
4      2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO   
...           ...          ...     ...         ...        ...   
8698            0          NaN     NaN         NaN        NaN   
8699            0          NaN     NaN         NaN        NaN   
8700            0          NaN     NaN         NaN        NaN   
8701            0          NaN     NaN         NaN        NaN   
25722          xx          NaN     NaN         NaN        NaN   

                  Area                        Location     Activity  \
0           California     Oceanside, San Diego County     Paddling   
1              Georgia  St. Simon Island, Glynn County     Standing   
2               Hawaii                    Habush, Oahu      Surfing   
3      New South Wales              Arrawarra Headland      Surfing   
4               Colima                        La Ticla  Free diving   
...                ...                             ...          ...   
8698               NaN                             NaN          NaN   
8699               NaN                             NaN          NaN   
8700               NaN                             NaN          NaN   
8701               NaN                             NaN          NaN   
25722              NaN                             NaN          NaN   

                  Name Sex   Age  \
0          Julie Wolfe    F   57   
1      Adyson McNeely     F   11   
2          John Denges    M   48   
3                 male    M  NaN   
4       Gustavo Ramos     M  NaN   
...                ...  ...  ...   
8698               NaN  NaN  NaN   
8699               NaN  NaN  NaN   
8700               NaN  NaN  NaN   
8701               NaN  NaN  NaN   
25722              NaN  NaN  NaN   

                                                  Injury Fatal (Y/N)  \
0      No injury to occupant, outrigger canoe and pad...           N   
1                             Minor injury to left thigh           N   
2           Injury to left lower leg from surfboard skeg           N   
3                              Minor injury to lower leg           N   
4      Lacerations to leg & hand shark PROVOKED INCIDENT           N   
...                                                  ...         ...   
8698                                                 NaN         NaN   
8699                                                 NaN         NaN   
8700                                                 NaN         NaN   
8701                                                 NaN         NaN   
25722                                                NaN         NaN   

                Time         Species   
0              18h00      White shark  
1      14h00  -15h00              NaN  
2              07h45              NaN  
3                NaN        2 m shark  
4                NaN  Tiger shark, 3m  
...              ...              ...  
8698             NaN              NaN  
8699             NaN              NaN  
8700             NaN              NaN  
8701             NaN              NaN  
25722            NaN              NaN  

[8703 rows x 15 columns]

In [10]:
#2.6
data_limpo3 = data_limpo2.drop_duplicates()
data_limpo3 

Case Number         Date    Year        Type             Country  \
0      2018.06.25  25-Jun-2018  2018.0     Boating                 USA   
1      2018.06.18  18-Jun-2018  2018.0  Unprovoked                 USA   
2      2018.06.09  09-Jun-2018  2018.0     Invalid                 USA   
3      2018.06.08  08-Jun-2018  2018.0  Unprovoked           AUSTRALIA   
4      2018.06.04  04-Jun-2018  2018.0    Provoked              MEXICO   
...           ...          ...     ...         ...                 ...   
6299      ND.0003    1900-1905     0.0  Unprovoked                 USA   
6300      ND.0002    1883-1889     0.0  Unprovoked              PANAMA   
6301      ND.0001    1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)   
6302            0          NaN     NaN         NaN                 NaN   
25722          xx          NaN     NaN         NaN                 NaN   

                   Area                             Location     Activity  \
0            California          Oceanside, San Diego County     Paddling   
1               Georgia       St. Simon Island, Glynn County     Standing   
2                Hawaii                         Habush, Oahu      Surfing   
3       New South Wales                   Arrawarra Headland      Surfing   
4                Colima                             La Ticla  Free diving   
...                 ...                                  ...          ...   
6299     North Carolina                       Ocracoke Inlet     Swimming   
6300                NaN                 Panama Bay 8єN, 79єW          NaN   
6301   Eastern Province  Below the English fort, Trincomalee     Swimming   
6302                NaN                                  NaN          NaN   
25722               NaN                                  NaN          NaN   

                        Name Sex   Age  \
0                Julie Wolfe    F   57   
1            Adyson McNeely     F   11   
2                John Denges    M   48   
3                       male    M  NaN   
4             Gustavo Ramos     M  NaN   
...                      ...  ...  ...   
6299   Coast Guard personnel    M  NaN   
6300         Jules Patterson    M  NaN   
6301                    male    M   15   
6302                     NaN  NaN  NaN   
25722                    NaN  NaN  NaN   

                                                  Injury Fatal (Y/N)  \
0      No injury to occupant, outrigger canoe and pad...           N   
1                             Minor injury to left thigh           N   
2           Injury to left lower leg from surfboard skeg           N   
3                              Minor injury to lower leg           N   
4      Lacerations to leg & hand shark PROVOKED INCIDENT           N   
...                                                  ...         ...   
6299                                               FATAL           Y   
6300                                               FATAL           Y   
6301   FATAL. "Shark bit him in half, carrying away t...           Y   
6302                                                 NaN         NaN   
25722                                                NaN         NaN   

                Time         Species   
0              18h00      White shark  
1      14h00  -15h00              NaN  
2              07h45              NaN  
3                NaN        2 m shark  
4                NaN  Tiger shark, 3m  
...              ...              ...  
6299             NaN              NaN  
6300             NaN              NaN  
6301             NaN              NaN  
6302             NaN              NaN  
25722            NaN              NaN  

[6304 rows x 15 columns]

In [11]:
#2.7
data_limpo3 = data_limpo3.drop([6302,25722])
data_limpo3

Case Number         Date    Year        Type             Country  \
0     2018.06.25  25-Jun-2018  2018.0     Boating                 USA   
1     2018.06.18  18-Jun-2018  2018.0  Unprovoked                 USA   
2     2018.06.09  09-Jun-2018  2018.0     Invalid                 USA   
3     2018.06.08  08-Jun-2018  2018.0  Unprovoked           AUSTRALIA   
4     2018.06.04  04-Jun-2018  2018.0    Provoked              MEXICO   
...          ...          ...     ...         ...                 ...   
6297     ND.0005  Before 1903     0.0  Unprovoked           AUSTRALIA   
6298     ND.0004  Before 1903     0.0  Unprovoked           AUSTRALIA   
6299     ND.0003    1900-1905     0.0  Unprovoked                 USA   
6300     ND.0002    1883-1889     0.0  Unprovoked              PANAMA   
6301     ND.0001    1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)   

                   Area                             Location      Activity  \
0            California          Oceanside, San Diego County      Paddling   
1               Georgia       St. Simon Island, Glynn County      Standing   
2                Hawaii                         Habush, Oahu       Surfing   
3       New South Wales                   Arrawarra Headland       Surfing   
4                Colima                             La Ticla   Free diving   
...                 ...                                  ...           ...   
6297  Western Australia                          Roebuck Bay        Diving   
6298  Western Australia                                  NaN  Pearl diving   
6299     North Carolina                       Ocracoke Inlet      Swimming   
6300                NaN                 Panama Bay 8єN, 79єW           NaN   
6301   Eastern Province  Below the English fort, Trincomalee      Swimming   

                       Name Sex   Age  \
0               Julie Wolfe    F   57   
1           Adyson McNeely     F   11   
2               John Denges    M   48   
3                      male    M  NaN   
4            Gustavo Ramos     M  NaN   
...                     ...  ...  ...   
6297                   male    M  NaN   
6298                  Ahmun    M  NaN   
6299  Coast Guard personnel    M  NaN   
6300        Jules Patterson    M  NaN   
6301                   male    M   15   

                                                 Injury Fatal (Y/N)  \
0     No injury to occupant, outrigger canoe and pad...           N   
1                            Minor injury to left thigh           N   
2          Injury to left lower leg from surfboard skeg           N   
3                             Minor injury to lower leg           N   
4     Lacerations to leg & hand shark PROVOKED INCIDENT           N   
...                                                 ...         ...   
6297                                              FATAL           Y   
6298                                              FATAL           Y   
6299                                              FATAL           Y   
6300                                              FATAL           Y   
6301  FATAL. "Shark bit him in half, carrying away t...           Y   

               Time         Species   
0             18h00      White shark  
1     14h00  -15h00              NaN  
2             07h45              NaN  
3               NaN        2 m shark  
4               NaN  Tiger shark, 3m  
...             ...              ...  
6297            NaN              NaN  
6298            NaN              NaN  
6299            NaN              NaN  
6300            NaN              NaN  
6301            NaN              NaN  

[6302 rows x 15 columns]

In [12]:
# 2.8 - vamos padronizar as colunas

In [13]:
old_columns = data_limpo3.columns
old_columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species '],
      dtype='object')

In [14]:
import re
pattern = '[\w_]+@[a-z]'

new_columns = [re.sub(pattern, "_", column.lower().strip()) for column in data_limpo3.columns]

In [15]:
data_limpo3.columns = new_columns
data_limpo3.head()

case number         date    year        type    country             area  \
0  2018.06.25  25-Jun-2018  2018.0     Boating        USA       California   
1  2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA          Georgia   
2  2018.06.09  09-Jun-2018  2018.0     Invalid        USA           Hawaii   
3  2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA  New South Wales   
4  2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO           Colima   

                         location     activity             name sex  age  \
0     Oceanside, San Diego County     Paddling      Julie Wolfe   F   57   
1  St. Simon Island, Glynn County     Standing  Adyson McNeely    F   11   
2                    Habush, Oahu      Surfing      John Denges   M   48   
3              Arrawarra Headland      Surfing             male   M  NaN   
4                        La Ticla  Free diving   Gustavo Ramos    M  NaN   

                                              injury fatal (y/n)  \
0  No injury to occupant, outrigger canoe and pad...           N   
1                         Minor injury to left thigh           N   
2       Injury to left lower leg from surfboard skeg           N   
3                          Minor injury to lower leg           N   
4  Lacerations to leg & hand shark PROVOKED INCIDENT           N   

            time          species  
0          18h00      White shark  
1  14h00  -15h00              NaN  
2          07h45              NaN  
3            NaN        2 m shark  
4            NaN  Tiger shark, 3m

In [16]:
data_limpo3.columns

Index(['case number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal (y/n)', 'time',
       'species'],
      dtype='object')

In [28]:
#2.9
df = data_limpo3.rename(columns={'sex':'gender'})

In [29]:
df.head()

case number         date    year        type    country             area  \
0  2018.06.25  25-Jun-2018  2018.0     Boating        USA       California   
1  2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA          Georgia   
2  2018.06.09  09-Jun-2018  2018.0     Invalid        USA           Hawaii   
3  2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA  New South Wales   
4  2018.06.04  04-Jun-2018  2018.0    Provoked     MEXICO           Colima   

                         location     activity             name gender  age  \
0     Oceanside, San Diego County     Paddling      Julie Wolfe      F   57   
1  St. Simon Island, Glynn County     Standing  Adyson McNeely       F   11   
2                    Habush, Oahu      Surfing      John Denges      M   48   
3              Arrawarra Headland      Surfing             male      M  NaN   
4                        La Ticla  Free diving   Gustavo Ramos       M  NaN   

                                              injury fatal (y/n)  \
0  No injury to occupant, outrigger canoe and pad...           N   
1                         Minor injury to left thigh           N   
2       Injury to left lower leg from surfboard skeg           N   
3                          Minor injury to lower leg           N   
4  Lacerations to leg & hand shark PROVOKED INCIDENT           N   

            time          species  
0          18h00      White shark  
1  14h00  -15h00              NaN  
2          07h45              NaN  
3            NaN        2 m shark  
4            NaN  Tiger shark, 3m

# 3.0 - Vamos tratar os dados referentes a coluna 'activity'. 
Essa é a coluna de principal importância para nós, pois ela registra as atividades que os acidentados estavam executando, e de certa forma, registra quem estava praticando pesca (que mais pra frente filtraremos entre pesca ilegal ou não)

3.1 - Leituras iniciais - usando o **count** o **unique()** e o **value_counts**

3.2 - Retiramos os valores nulos da coluna ACTIVITY

3.3 - Aqui criaremos uma título especial abaixo, chamado _transformando nomes_, pois muitos nomes não estão padronizados de acordo com uma lógica pré estabelecida. Ao mesmo tempo que temos o input "Fishing" nós também temos "Fishing from surf ski". Portanto transformamos tudo que tenha o termo fishing ou Fishing em apenas "fishing"

3.4 - Retiramos as linhas que possuiam pouca frquência 

3.5 - por fim, faremos algumas leituras para entendimento do resultado final 

# 3.1 - Leituras Iniciais

In [30]:

df['activity'].count()

5758

In [31]:
df['activity'].nunique()

1532

In [32]:
df['activity'].value_counts()

Surfing                                   971
Swimming                                  869
Fishing                                   431
Spearfishing                              333
Bathing                                   162
                                         ... 
Playing with a frisbee in the shallows      1
Sinking of the ferryboat Dumaguete          1
Wreck of the Storm King                     1
Feeding mullet to sharks                    1
Wreck of  large double sailing canoe        1
Name: activity, Length: 1532, dtype: int64

In [33]:
df['activity'].value_counts(normalize = True)*100

Surfing                                   16.863494
Swimming                                  15.092046
Fishing                                    7.485238
Spearfishing                               5.783258
Bathing                                    2.813477
                                            ...    
Playing with a frisbee in the shallows     0.017367
Sinking of the ferryboat Dumaguete         0.017367
Wreck of the Storm King                    0.017367
Feeding mullet to sharks                   0.017367
Wreck of  large double sailing canoe       0.017367
Name: activity, Length: 1532, dtype: float64

# 3.2 - retirando valores nulos

In [77]:
df_act_limpo= df.dropna(subset=['activity'])
df_act_limpo

case number         date    year        type             country  \
0     2018.06.25  25-Jun-2018  2018.0     Boating                 USA   
1     2018.06.18  18-Jun-2018  2018.0  Unprovoked                 USA   
2     2018.06.09  09-Jun-2018  2018.0     Invalid                 USA   
3     2018.06.08  08-Jun-2018  2018.0  Unprovoked           AUSTRALIA   
4     2018.06.04  04-Jun-2018  2018.0    Provoked              MEXICO   
...          ...          ...     ...         ...                 ...   
6296     ND.0006  Before 1906     0.0  Unprovoked           AUSTRALIA   
6297     ND.0005  Before 1903     0.0  Unprovoked           AUSTRALIA   
6298     ND.0004  Before 1903     0.0  Unprovoked           AUSTRALIA   
6299     ND.0003    1900-1905     0.0  Unprovoked                 USA   
6301     ND.0001    1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)   

                   area                             location      activity  \
0            California          Oceanside, San Diego County      Paddling   
1               Georgia       St. Simon Island, Glynn County      Standing   
2                Hawaii                         Habush, Oahu       Surfing   
3       New South Wales                   Arrawarra Headland       Surfing   
4                Colima                             La Ticla   Free diving   
...                 ...                                  ...           ...   
6296    New South Wales                                           Swimming   
6297  Western Australia                          Roebuck Bay        Diving   
6298  Western Australia                                  NaN  Pearl diving   
6299     North Carolina                       Ocracoke Inlet      Swimming   
6301   Eastern Province  Below the English fort, Trincomalee      Swimming   

                       name gender  age  \
0               Julie Wolfe      F   57   
1           Adyson McNeely       F   11   
2               John Denges      M   48   
3                      male      M  NaN   
4            Gustavo Ramos       M  NaN   
...                     ...    ...  ...   
6296               Arab boy      M  NaN   
6297                   male      M  NaN   
6298                  Ahmun      M  NaN   
6299  Coast Guard personnel      M  NaN   
6301                   male      M   15   

                                                 injury fatal (y/n)  \
0     No injury to occupant, outrigger canoe and pad...           N   
1                            Minor injury to left thigh           N   
2          Injury to left lower leg from surfboard skeg           N   
3                             Minor injury to lower leg           N   
4     Lacerations to leg & hand shark PROVOKED INCIDENT           N   
...                                                 ...         ...   
6296                                              FATAL           Y   
6297                                              FATAL           Y   
6298                                              FATAL           Y   
6299                                              FATAL           Y   
6301  FATAL. "Shark bit him in half, carrying away t...           Y   

               time                                            species  
0             18h00                                        White shark  
1     14h00  -15h00                                                NaN  
2             07h45                                                NaN  
3               NaN                                          2 m shark  
4               NaN                                    Tiger shark, 3m  
...             ...                                                ...  
6296            NaN  Said to involve a grey nurse shark that leapt ...  
6297            NaN                                                NaN  
6298            NaN                                                NaN  
6299            NaN                                                NaN  
6301            Na

In [78]:
df_act_limpo.isnull().sum()

case number       1
date              0
year              2
type              4
country          43
area            376
location        453
activity          0
name            151
gender          414
age            2429
injury           16
fatal (y/n)     414
time           2876
species        2523
dtype: int64

# 3.3 - transformando termos:
aqui estamos transformando tudo que tem a palavra fishing em apenas 'fishing'

In [82]:
##aqui colocamos o nome da coluna e logo em seguida colocamos os termos que queremos encontrar e substituir pela palavra que colocamos logo em seguida, no caso abaixo é fishing
df_act_limpo.loc[df_act_limpo['activity'].str.contains('fishing|Fishing|Spearfishing'),'activity'] = 'fishing'
df_act_limpo['activity'].value_counts()


fishing                                                                                                                                                 1161
swimming                                                                                                                                                1117
Surfing                                                                                                                                                  971
Bathing                                                                                                                                                  162
Wading                                                                                                                                                   149
                                                                                                                                                        ... 
Diving. Shark “swallowed’ his hand, so he threw his other 

In [83]:
df_act_limpo.loc[df_act_limpo['activity'].str.contains('Swimming|swimming|swimming '), 'activity'] = 'swimming'
df_act_limpo['activity'].value_counts()

fishing                                                                                                                                                 1161
swimming                                                                                                                                                1117
Surfing                                                                                                                                                  971
Bathing                                                                                                                                                  162
Wading                                                                                                                                                   149
                                                                                                                                                        ... 
Diving. Shark “swallowed’ his hand, so he threw his other 

In [84]:
df_act_limpo.loc[df_act_limpo['activity'].str.contains('Diving|diving|Dived'), 'activity'] = 'diving'
df_act_limpo['activity'].value_counts()

fishing                                                                                                             1161
swimming                                                                                                            1117
Surfing                                                                                                              971
diving                                                                                                               540
Bathing                                                                                                              162
                                                                                                                    ... 
A father bathing his smallest daughter when the shark bumped her out of his arms and carried her into deep water       1
Hunting crayfish                                                                                                       1
Netting sharks                  

In [85]:
df_act_limpo.loc[df_act_limpo['activity'].str.contains('Attempting|attempting'), 'activity'] = 'attempting'
df_act_limpo['activity'].value_counts()

fishing                                                                                                                                                  1161
swimming                                                                                                                                                 1117
Surfing                                                                                                                                                   971
diving                                                                                                                                                    540
Bathing                                                                                                                                                   162
                                                                                                                                                         ... 
The passenger ship Pioneer Cebu  capsized & sank in 

In [101]:
df_act_limpo.loc[df_act_limpo['activity'].str.contains('Surfing|surfing'), 'activity'] = 'surfing'
df_act_limpo['activity'].value_counts()

fishing                                             1161
surfing                                             1120
swimming                                            1117
diving                                               540
Bathing                                              162
                                                    ... 
Floating on his back in an inner tube                  1
Searching for remains of  Dr. Marais                   1
Yacht Gooney Bird foundered, 4 survivors on raft       1
canoeing                                               1
Wreck of  large double sailing canoe                   1
Name: activity, Length: 811, dtype: int64

In [102]:
df_act_limpo.loc[df_act_limpo['activity'].str.contains('Surf skiing|Surf-skiing'), 'activity'] = 'surf_skiing'
df_act_limpo['activity'].value_counts()

fishing                                             1161
surfing                                             1120
swimming                                            1117
diving                                               540
Bathing                                              162
                                                    ... 
Floating on his back in an inner tube                  1
Searching for remains of  Dr. Marais                   1
Yacht Gooney Bird foundered, 4 survivors on raft       1
canoeing                                               1
Wreck of  large double sailing canoe                   1
Name: activity, Length: 811, dtype: int64

**outr maneira de executar, usando apply:**
def limpa_ativ(row): 
    row = row.lower()  
    if 'fishing' in row: 
        return 'fishing'
    elif 'swimming' in row: 
        return 'swimming'
    else: 
        return 'validar'

**verificando se a função funciona**
limpa_ativ('fishing inside the ocean')

**validando a função** 
data['Activity'].dropna().apply(limpa_ativ)

# 3.4 - retirando linhas com frequência muito baixa

In [103]:
col = 'activity'  
n = 3       

df_act= df_act_limpo[df_act_limpo.groupby('activity')['activity'].transform('count').ge(10)]
df_act

case number         date    year        type             country  \
1       2018.06.18  18-Jun-2018  2018.0  Unprovoked                 USA   
2       2018.06.09  09-Jun-2018  2018.0     Invalid                 USA   
3       2018.06.08  08-Jun-2018  2018.0  Unprovoked           AUSTRALIA   
4       2018.06.04  04-Jun-2018  2018.0    Provoked              MEXICO   
5     2018.06.03.b  03-Jun-2018  2018.0  Unprovoked           AUSTRALIA   
...            ...          ...     ...         ...                 ...   
6296       ND.0006  Before 1906     0.0  Unprovoked           AUSTRALIA   
6297       ND.0005  Before 1903     0.0  Unprovoked           AUSTRALIA   
6298       ND.0004  Before 1903     0.0  Unprovoked           AUSTRALIA   
6299       ND.0003    1900-1905     0.0  Unprovoked                 USA   
6301       ND.0001    1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)   

                   area                             location  activity  \
1               Georgia       St. Simon Island, Glynn County  Standing   
2                Hawaii                         Habush, Oahu   surfing   
3       New South Wales                   Arrawarra Headland   surfing   
4                Colima                             La Ticla    diving   
5       New South Wales                   Flat Rock, Ballina   surfing   
...                 ...                                  ...       ...   
6296    New South Wales                                       swimming   
6297  Western Australia                          Roebuck Bay    diving   
6298  Western Australia                                  NaN    diving   
6299     North Carolina                       Ocracoke Inlet  swimming   
6301   Eastern Province  Below the English fort, Trincomalee  swimming   

                       name gender  age  \
1           Adyson McNeely       F   11   
2               John Denges      M   48   
3                      male      M  NaN   
4            Gustavo Ramos       M  NaN   
5                   Chris …      M  NaN   
...                     ...    ...  ...   
6296               Arab boy      M  NaN   
6297                   male      M  NaN   
6298                  Ahmun      M  NaN   
6299  Coast Guard personnel      M  NaN   
6301                   male      M   15   

                                                 injury fatal (y/n)  \
1                            Minor injury to left thigh           N   
2          Injury to left lower leg from surfboard skeg           N   
3                             Minor injury to lower leg           N   
4     Lacerations to leg & hand shark PROVOKED INCIDENT           N   
5                               No injury, board bitten           N   
...                                                 ...         ...   
6296                                              FATAL           Y   
6297                                              FATAL           Y   
6298                                              FATAL           Y   
6299                                              FATAL           Y   
6301  FATAL. "Shark bit him in half, carrying away t...           Y   

               time                                            species  
1     14h00  -15h00                                                NaN  
2             07h45                                                NaN  
3               NaN                                          2 m shark  
4               NaN                                    Tiger shark, 3m  
5               NaN                                                NaN  
...             ...                                                ...  
6296            NaN  Said to involve a grey nurse shark that leapt ...  
6297            NaN                                                NaN  
6298            NaN                                                NaN  
6299            NaN                                                NaN  
6301            NaN                         

# 3.5 - análises finais 

In [104]:
df_act['activity'].value_counts()

fishing            1161
surfing            1120
swimming           1117
diving              540
Bathing             162
Wading              149
Standing             99
Snorkeling           89
Body boarding        61
Kayaking             33
attempting           32
Treading water       32
Fell overboard       32
surf_skiing          31
Boogie boarding      29
Walking              17
Boogie Boarding      16
Floating             14
Canoeing             13
Rowing               12
Name: activity, dtype: int64

In [105]:
df_act['activity'].value_counts(normalize=True)*100

fishing            24.395881
surfing            23.534356
swimming           23.471318
diving             11.346922
Bathing             3.404076
Wading              3.130910
Standing            2.080269
Snorkeling          1.870141
Body boarding       1.281782
Kayaking            0.693423
attempting          0.672410
Treading water      0.672410
Fell overboard      0.672410
surf_skiing         0.651397
Boogie boarding     0.609372
Walking             0.357218
Boogie Boarding     0.336205
Floating            0.294179
Canoeing            0.273167
Rowing              0.252154
Name: activity, dtype: float64

# Resumo até o momento 

As seguintes alterações foi feitas: 
-> nulos retirados 

-> ocorrências baixas retiradas 

-> atividades renomadas 

Nossa planilha final tem nome de: **df_act** 

# 4.0 - Vamos tratar os dados referentes a coluna 'contry' e 'area'. 
Essa coluna é importante pois ela nos elucidará sobre o local no qual as atividades estavam sendo executadas, tendo como base o filtro anterior. Para a nossa análise, o mais importante é compreender a relação localização X pesca.

4.1 - Leituras iniciais - usando o **count** o **unique()** e o **value_counts**

4.2 - Vamos Limpar essa coluna também, pois não nos importa casos com inputs menores de 80



# 4.1 - leituras iniciais

In [106]:
df_act['country'].nunique() ##temos 170 inputs para países 

170

In [107]:
df_act['country'].value_counts() ##temos 170 inputs para países 

USA                               1806
AUSTRALIA                         1035
SOUTH AFRICA                       463
NEW ZEALAND                        102
PAPUA NEW GUINEA                    92
                                  ... 
FEDERATED STATES OF MICRONESIA       1
SOUTH PACIFIC OCEAN                  1
COMOROS                              1
BRITISH ISLES                        1
CEYLON (SRI LANKA)                   1
Name: country, Length: 170, dtype: int64

In [108]:
df_act['area'].nunique() ##temos 591 inputs para áreas 

591

In [109]:
df_act['area'].value_counts() ##temos que Flórida e NewSouth

Florida                                  880
New South Wales                          379
California                               249
Hawaii                                   230
Queensland                               221
                                        ... 
Clearwater Bay                             1
Chatham Islands, east of New  Zealand      1
Saint-Paul                                 1
Missouri                                   1
Ba Ria-Vung Tau  Province                  1
Name: area, Length: 591, dtype: int64

# 4.2 - Aqui estamos limpando as ocorrências de menor frequência,
como estamos procurando os lugares com maiores ocorrências, não faz sentido nos preocuparmos com localidades que tenham menos de 80 casos

In [110]:
col = 'country' 
n = 50     

df_cou= df_act[df_act.groupby('country')['country'].transform('count').ge(80)]
df_cou['country'].value_counts(normalize=True)

USA                 0.491830
AUSTRALIA           0.281863
SOUTH AFRICA        0.126089
NEW ZEALAND         0.027778
PAPUA NEW GUINEA    0.025054
BRAZIL              0.024782
BAHAMAS             0.022603
Name: country, dtype: float64

In [111]:
df_cou.query('activity =="fishing"').count()


case number    838
date           839
year           838
type           839
country        839
area           814
location       800
activity       839
name           829
gender         712
age            387
injury         838
fatal (y/n)    786
time           328
species        614
dtype: int64

In [112]:
df_cou

case number         date    year        type    country  \
1       2018.06.18  18-Jun-2018  2018.0  Unprovoked        USA   
2       2018.06.09  09-Jun-2018  2018.0     Invalid        USA   
3       2018.06.08  08-Jun-2018  2018.0  Unprovoked  AUSTRALIA   
5     2018.06.03.b  03-Jun-2018  2018.0  Unprovoked  AUSTRALIA   
6     2018.06.03.a  03-Jun-2018  2018.0  Unprovoked     BRAZIL   
...            ...          ...     ...         ...        ...   
6295       ND.0007  Before 1906     0.0  Unprovoked  AUSTRALIA   
6296       ND.0006  Before 1906     0.0  Unprovoked  AUSTRALIA   
6297       ND.0005  Before 1903     0.0  Unprovoked  AUSTRALIA   
6298       ND.0004  Before 1903     0.0  Unprovoked  AUSTRALIA   
6299       ND.0003    1900-1905     0.0  Unprovoked        USA   

                   area                        location  activity  \
1               Georgia  St. Simon Island, Glynn County  Standing   
2                Hawaii                    Habush, Oahu   surfing   
3       New South Wales              Arrawarra Headland   surfing   
5       New South Wales              Flat Rock, Ballina   surfing   
6            Pernambuco           Piedade Beach, Recife  swimming   
...                 ...                             ...       ...   
6295                NaN                             NaN   fishing   
6296    New South Wales                                  swimming   
6297  Western Australia                     Roebuck Bay    diving   
6298  Western Australia                             NaN    diving   
6299     North Carolina                  Ocracoke Inlet  swimming   

                        name gender  age  \
1            Adyson McNeely       F   11   
2                John Denges      M   48   
3                       male      M  NaN   
5                    Chris …      M  NaN   
6     Jose Ernesto da Silva       M   18   
...                      ...    ...  ...   
6295               fisherman      M  NaN   
6296                Arab boy      M  NaN   
6297                    male      M  NaN   
6298                   Ahmun      M  NaN   
6299   Coast Guard personnel      M  NaN   

                                            injury fatal (y/n)  \
1                       Minor injury to left thigh           N   
2     Injury to left lower leg from surfboard skeg           N   
3                        Minor injury to lower leg           N   
5                          No injury, board bitten           N   
6                                            FATAL           Y   
...                                            ...         ...   
6295                                         FATAL           Y   
6296                                         FATAL           Y   
6297                                         FATAL           Y   
6298                                         FATAL           Y   
6299                                         FATAL           Y   

                time                                            species  
1      14h00  -15h00                                                NaN  
2              07h45                                                NaN  
3                NaN                                          2 m shark  
5                NaN                                                NaN  
6     Late afternoon                                        Tiger shark  
...              ...                                                ...  
6295             NaN                                      Blue pointers  
6296             NaN  Said to involve a grey nurse shark that leapt ...  
6297             NaN                                                NaN  
6298             NaN                                                NaN  
6299             NaN                                                NaN  

[3672 rows x 15 columns]

# 4.3 - Aqui relacionaremos 'country' x 'area'
É importante analisarmos este dado, pois podemos concatenar com as práticas envolvidas . Aqui daremos um **groupby**, agrupando country e area - utilizaremos a função **size** para saber quantos casos aconteceram ns cidades referidas e também usaremos o **sort_values** para trazer as cidades com maior incidência em primeiro lugar. 

In [113]:
##aqui podemos perceber que a maior quantidade de casos aconteceu na Flórida e em New South Wales
print(df_cou.groupby(["country", "area"]).size().sort_values(ascending=False))

country           area               
USA               Florida                880
AUSTRALIA         New South Wales        379
USA               California             249
                  Hawaii                 230
AUSTRALIA         Queensland             221
                                        ... 
BAHAMAS           New Providence           1
                  New Providence           1
PAPUA NEW GUINEA   Kikori River mouth      1
NEW ZEALAND       South Island?            1
PAPUA NEW GUINEA  Rigo subdistrict         1
Length: 121, dtype: int64


In [114]:
#colocamos o reset.index para reverter a lógica do groupby, que transforma as colunas chamadas em index
df_group = df_cou.groupby(["country", "area"]).count()[['case number']].reset_index()
df_group[(df_group['country']== 'USA')|(df_group['country']== 'AUSTRALIA')].sort_values(['country','case number'],ascending = False) 

country                                  area  case number
92         USA                               Florida          879
89         USA                            California          249
95         USA                                Hawaii          230
115        USA                        South Carolina          104
109        USA                        North Carolina           86
116        USA                                 Texas           54
104        USA                            New Jersey           38
111        USA                                Oregon           28
106        USA                              New York           25
101        USA                         Massachusetts           13
118        USA                              Virginia           13
88         USA                               Alabama           12
93         USA                               Georgia            9
98         USA                             Louisiana            8
113        USA                           Puerto Rico            8
100        USA                              Maryland            7
114        USA                          Rhode Island            7
91         USA                              Delaware            6
117        USA                     US Virgin Islands            5
90         USA                           Connecticut            3
102        USA                           Mississippi            3
107        USA                             New York             3
110        USA                       North Carolina             2
120        USA                            Washington            2
94         USA                                  Guam            1
96         USA                              Illinois            1
97         USA                        Johnston Atoll            1
99         USA                                 Maine            1
103        USA                              Missouri            1
105        USA                            New Mexico            1
108        USA                North & South Carolina            1
112        USA                         Palmyra Atoll            1
119        USA                           Wake Island            1
0    AUSTRALIA                       New South Wales          379
3    AUSTRALIA                            Queensland          221
13   AUSTRALIA                     Western Australia          150
5    AUSTRALIA                       South Australia           85
10   AUSTRALIA                              Victoria           73
8    AUSTRALIA                         Torres Strait           60
6    AUSTRALIA                              Tasmania           31
2    AUSTRALIA                    Northern Territory           16
9    AUSTRALIA                        Torres Strait             2
11   AUSTRALIA                             Victoria             2
12   AUSTRALIA                     Westerm Australia            2
1    AUSTRALIA                        Norfolk Island            1
4    AUSTRALIA                           Queensland             1
7    AUSTRALIA  Territory of Cocos (Keeling) Islands            1

# 5.0 - Aqui analisaremos a coluna "type". 
5.1 - Aplicamos o comando **.unique()** para enterdermos quantos valores unicos existem dentro da coluna

5.2 - Aplicamos o comando **.value_counts()** para enterdermos os quantitativos de cada input e logo em seguida usaremos o **.value_counts(normalize=True)** para obtermos o mesmo valor em porcentagem. É interessante perceber que apenas 574 casos foram classificados como "provoked", aproximadamente 9% dos casos registrados. 

# 5.1 - Leituras iniciais

In [115]:
df_cou['type'].unique()

array(['Unprovoked', 'Invalid', 'Questionable', 'Provoked', 'Boating',
       nan, 'Boat', 'Boatomg', 'Sea Disaster'], dtype=object)

In [116]:
df_cou['type'].count()

3671

In [117]:
#5.2
df_cou['type'].value_counts()

Unprovoked      2883
Provoked         327
Invalid          264
Boating          114
Boat              70
Sea Disaster      10
Questionable       2
Boatomg            1
Name: type, dtype: int64

In [118]:
#5.2
df_cou['type'].value_counts(normalize = True)*100

Unprovoked      78.534459
Provoked         8.907655
Invalid          7.191501
Boating          3.105421
Boat             1.906837
Sea Disaster     0.272405
Questionable     0.054481
Boatomg          0.027241
Name: type, dtype: float64

In [119]:
print(df_cou.groupby(["area", "type"]).size().sort_values(ascending=False).to_markdown())

|                                                                |   0 |
|:---------------------------------------------------------------|----:|
| ('Florida', 'Unprovoked')                                      | 762 |
| ('New South Wales', 'Unprovoked')                              | 285 |
| ('Hawaii', 'Unprovoked')                                       | 191 |
| ('Queensland', 'Unprovoked')                                   | 170 |
| ('California', 'Unprovoked')                                   | 166 |
| ('KwaZulu-Natal', 'Unprovoked')                                | 118 |
| ('Eastern Cape Province', 'Unprovoked')                        | 115 |
| ('Western Cape Province', 'Unprovoked')                        | 113 |
| ('Western Australia', 'Unprovoked')                            | 106 |
| ('South Carolina', 'Unprovoked')                               |  85 |
| ('North Carolina', 'Unprovoked')                               |  74 |
| ('Florida', 'Provoked')                          

In [120]:
df_cou.groupby('country').agg({'area':'size','type':'size'})

area  type
country                     
AUSTRALIA         1035  1035
BAHAMAS             83    83
BRAZIL              91    91
NEW ZEALAND        102   102
PAPUA NEW GUINEA    92    92
SOUTH AFRICA       463   463
USA               1806  1806

In [121]:
df_cou.columns

Index(['case number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'gender', 'age', 'injury', 'fatal (y/n)', 'time',
       'species'],
      dtype='object')

In [122]:
df_group2 = df_cou.groupby(["type", "activity"]).count()[['case number']].reset_index()
df_group2

type     activity  case number
0         Boat     Canoeing            1
1         Boat       Rowing            2
2         Boat   attempting            2
3         Boat      fishing           65
4      Boating     Canoeing            3
..         ...          ...          ...
58  Unprovoked       diving          291
59  Unprovoked      fishing          390
60  Unprovoked  surf_skiing           27
61  Unprovoked      surfing          978
62  Unprovoked     swimming          683

[63 rows x 3 columns]

In [123]:
df_group2[(df_group2['type']== 'Unprovoked')|(df_group2['type']== 'Provoked')].sort_values(['type','case number'],ascending = False) 

type         activity  case number
61  Unprovoked          surfing          978
62  Unprovoked         swimming          683
59  Unprovoked          fishing          390
58  Unprovoked           diving          291
55  Unprovoked           Wading          116
44  Unprovoked          Bathing           92
53  Unprovoked         Standing           83
52  Unprovoked       Snorkeling           56
45  Unprovoked    Body boarding           50
54  Unprovoked   Treading water           28
60  Unprovoked      surf_skiing           27
47  Unprovoked  Boogie boarding           25
56  Unprovoked          Walking           14
46  Unprovoked  Boogie Boarding           13
49  Unprovoked   Fell overboard           10
50  Unprovoked         Floating           10
57  Unprovoked       attempting            7
51  Unprovoked         Kayaking            6
48  Unprovoked         Canoeing            4
37    Provoked          fishing          242
36    Provoked           diving           34
39    Provoked          surfing           13
40    Provoked         swimming           10
35    Provoked       attempting            9
34    Provoked           Wading            6
32    Provoked       Snorkeling            5
30    Provoked         Canoeing            2
33    Provoked         Standing            2
29    Provoked  Boogie Boarding            1
31    Provoked           Rowing            1
38    Provoked      surf_skiing            1

# 6 - Vamos analisar o dado 'species'


In [124]:
df_cou['species'].count()

2261

In [386]:
df_cou['species'].nunique()

1098

In [388]:
df_sp= df_cou.dropna(subset=['species'])
df_sp.head()

case number         date    year          type    country  \
3     2018.06.08  08-Jun-2018  2018.0    Unprovoked  AUSTRALIA   
6   2018.06.03.a  03-Jun-2018  2018.0    Unprovoked     BRAZIL   
7     2018.05.27  27-May-2018  2018.0    Unprovoked        USA   
8   2018.05.26.b  26-May-2018  2018.0    Unprovoked        USA   
16    2018.05.09  09-May-2018  2018.0  Questionable  AUSTRALIA   

               area                                           location  \
3   New South Wales                                 Arrawarra Headland   
6        Pernambuco                              Piedade Beach, Recife   
7           Florida  Lighhouse Point Park, Ponce Inlet, Volusia County   
8           Florida                       Cocoa Beach, Brevard  County   
16  New South Wales                             Sharpes Beach, Ballina   

    activity                    name gender  age  \
3    surfing                    male      M  NaN   
6   swimming  Jose Ernesto da Silva       M   18   
7    fishing                    male      M   52   
8    Walking               Cody High      M   15   
16   surfing                    male      M  NaN   

                                     injury fatal (y/n)            time  \
3                 Minor injury to lower leg           N             NaN   
6                                     FATAL           Y  Late afternoon   
7   Minor injury to foot. PROVOKED INCIDENT           N             NaN   
8                     Lower left leg bitten           N           17h00   
16             No injury, surfboard damaged           N           10h30   

                            species  
3                         2 m shark  
6                       Tiger shark  
7                   Lemon shark, 3'  
8                    Bull shark, 6'  
16  Shark involvement not confirmed

In [389]:
df_sp.isnull().sum() 

case number      0
date             0
year             1
type             0
country          0
area            27
location        45
activity         0
name            19
gender         140
age            659
injury           4
fatal (y/n)    243
time           803
species          0
dtype: int64

In [390]:
df_sp['species'].count()

2261

In [391]:
df_sp.loc[df_sp['species'].str.contains('Tiger | tiger'), 'species'] = 'tiger_shark'
df_sp['species'].value_counts()

tiger_shark                                                                                                                      164
White shark                                                                                                                      117
Shark involvement not confirmed                                                                                                   59
Invalid                                                                                                                           48
Shark involvement prior to death was not confirmed                                                                                38
                                                                                                                                ... 
60 cm to 90 cm [2' to 3'] shark                                                                                                    1
White shark, 3.5 m [11.5']  male                                     

In [392]:
df_sp.loc[df_sp['species'].str.contains('white|White|White shark'), 'species'] = 'white_shark'
df_sp['species'].value_counts()

white_shark                                                                                                                      487
tiger_shark                                                                                                                      164
Shark involvement not confirmed                                                                                                   59
Invalid                                                                                                                           48
Shark involvement prior to death was not confirmed                                                                                38
                                                                                                                                ... 
1.2 m [4'] blacktip or sandbar shark                                                                                               1
Bull shark, 1.8 m to 2.1 m [6' to 7']                                

In [464]:
df_sp.loc[df_sp['species'].str.contains('not confirmed|Invalid|to|3|4|5|6|small|nose'), 'species'] = 'unkown'
df_sp['species'].value_counts(normalize= True)

unkown                      0.489164
white_shark                 0.215391
tiger_shark                 0.072534
Bull shark                  0.012826
Wobbegong shark             0.008846
                              ...   
Bronze whaler shark, 2 m    0.000442
Questionable Incident       0.000442
2 m cow shark               0.000442
2.1 m  [7'] bull shark      0.000442
Blue pointers               0.000442
Name: species, Length: 228, dtype: float64

In [465]:
df_sp.loc[df_sp['species'].str.contains('Lemon'), 'species'] = 'lemon_shark'
df_sp['species'].value_counts()

unkown                      1106
white_shark                  487
tiger_shark                  164
Bull shark                    29
Wobbegong shark               20
                            ... 
Bronze whaler shark, 2 m       1
Questionable Incident          1
2 m cow shark                  1
2.1 m  [7'] bull shark         1
Blue pointers                  1
Name: species, Length: 228, dtype: int64

In [466]:
col = 'species' 
n = 2       

df_sp_limpa= df_sp[df_sp.groupby('species')['species'].transform('count').ge(20)]
df_sp_limpa['species'].value_counts( )

unkown             1106
white_shark         487
tiger_shark         164
Bull shark           29
Wobbegong shark      20
Name: species, dtype: int64

In [467]:
###############paramos aqui - queremos colocar o filtro de fishing em activity diretamente no código
print(df_sp_limpa.groupby(["activity", "species","area"]).size().sort_values(ascending=False).to_markdown())

|                                                                       |   0 |
|:----------------------------------------------------------------------|----:|
| ('surfing', 'unkown', 'Florida')                                      | 155 |
| ('swimming', 'unkown', 'Florida')                                     |  50 |
| ('surfing', 'white_shark', 'California')                              |  49 |
| ('fishing', 'unkown', 'Florida')                                      |  40 |
| ('diving', 'white_shark', 'California')                               |  36 |
| ('fishing', 'white_shark', 'Western Cape Province')                   |  36 |
| ('surfing', 'tiger_shark', 'Hawaii')                                  |  35 |
| ('fishing', 'unkown', 'New South Wales')                              |  34 |
| ('Wading', 'unkown', 'Florida')                                       |  32 |
| ('swimming', 'unkown', 'New South Wales')                             |  29 |
| ('fishing', 'white_shark', 'California

In [463]:
# Query the database for Quantity greater than 3
x = df_sp.query('activity == "fishing"')
 
# Filter out labels of interest
x = x.filter(['species', 'area'])
 
# Group the value according to a condition
x.groupby('species').count().sort_index(ascending=False)

area
species                                
white_shark                         120
unkown                              296
tiger_shark                          32
sandtiger shark                       1
reef shark?                           1
...                                 ...
"a very large shark"                  1
"Blue nose sharks"                    1
"Attacked by a number of sharks"      1
"A long thin brown-colored shark"     1
 reef shark, 1.8m                     1

[110 rows x 1 columns]

In [471]:
df_fishing = df_sp_limpa.groupby(['area']).apply(lambda x: x[x['activity'] == 'fishing'])
df_fishing


case number                  date    year  \
area                                                                     
 Kikori River mouth   4108    1959.02.06           16-Feb-1959  1959.0   
10єS, 142єE           3850  1962.01.11.b           11-Jan-1962  1962.0   
Abaco Islands         241   2016.07.23.a           23-Jul-2016  2016.0   
                      539     2014.06.25           25-Jun-2014  2014.0   
                      646   2013.07.29.c           28-Jul-2013  2013.0   
...                                  ...                   ...     ...   
Western Cape Province 3959  1960.10.00.b              Oct-1960  1960.0   
                      4006  1960.04.00.a              Apr-1960  1960.0   
                      4047    1959.11.15           15-Nov-1959  1959.0   
                      4179  1958.00.00.b                  1958  1958.0   
                      4253  1956.05.26.R  Reported 26-May-1956  1956.0   

                                  type           country  \
area                                                       
 Kikori River mouth   4108    Provoked  PAPUA NEW GUINEA   
10єS, 142єE           3850  Unprovoked  PAPUA NEW GUINEA   
Abaco Islands         241   Unprovoked           BAHAMAS   
                      539   Unprovoked           BAHAMAS   
                      646   Unprovoked           BAHAMAS   
...                                ...               ...   
Western Cape Province 3959        Boat      SOUTH AFRICA   
                      4006        Boat      SOUTH AFRICA   
                      4047        Boat      SOUTH AFRICA   
                      4179        Boat      SOUTH AFRICA   
                      4253     Boating      SOUTH AFRICA   

                                             area  \
area                                                
 Kikori River mouth   4108     Kikori River mouth   
10єS, 142єE           3850            10єS, 142єE   
Abaco Islands         241           Abaco Islands   
                      539           Abaco Islands   
                      646           Abaco Islands   
...                                           ...   
Western Cape Province 3959  Western Cape Province   
                      4006  Western Cape Province   
                      4047  Western Cape Province   
                      4179  Western Cape Province   
                      4253  Western Cape Province   

                                                                  location  \
area                                                                         
 Kikori River mouth   4108  Ururumba, mouth of Kikori River 7.45S, 144.40E   
10єS, 142єE           3850                               Jukuataia Village   
Abaco Islands         241                                 Green Turtle Cay   
                      539                                              NaN   
                      646                                     Scotland Cay   
...                                                                    ...   
Western Cape Province 3959                                       False Bay   
                      4006                                    Saldanha Bay   
                      4047                            Swartklip, False Bay   
                      4179                                 Plettenberg Bay   
                      4253                                 Plettenberg Bay   

                           activity  \
area                                  
 Kikori River mouth   4108  fishing   
10єS, 142єE           3850  fishing   
Abaco Islands         241   fishing   
                      539   fishing   
                      646   fishing   
...                             ...   
Western Cape Province 3959  fishing   
                      4006  fishing   
                      4047  fishing   
                      4179  fishing   
                      4253  fishing   

                                                                       n